# Generated by Django 5.1.3 on 2025-01-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
